#!/bin/bash
#
# Baseline this host (before any test application install), run script as root

rightnow=$(date +%Y-%m-%d)
systemhostname=$(hostname | cut -d '.' -f 1)
out=("$systemhostname")

mkdir system-summary before after diff



# Get system summary

echo 'Current date' >> system-summary/$out-host-summary-$rightnow.txt
echo '---------------------------------------------------------------------------------------------' >> system-summary/$out-host-summary-$rightnow.txt
date >> system-summary/$out-host-summary-$rightnow.txt
echo '' >> system-summary/$out-host-summary-$rightnow.txt
echo '' >> system-summary/$out-host-summary-$rightnow.txt

echo 'System hostname' >> system-summary/$out-host-summary-$rightnow.txt
echo '---------------------------------------------------------------------------------------------' >> system-summary/$out-host-summary-$rightnow.txt
hostname >> system-summary/$out-host-summary-$rightnow.txt
echo '' >> system-summary/$out-host-summary-$rightnow.txt
echo '' >> system-summary/$out-host-summary-$rightnow.txt

echo 'Kernel version' >> system-summary/$out-host-summary-$rightnow.txt
echo '---------------------------------------------------------------------------------------------' >> system-summary/$out-host-summary-$rightnow.txt
uname -r >> system-summary/$out-host-summary-$rightnow.txt
echo '' >> system-summary/$out-host-summary-$rightnow.txt
echo '' >> system-summary/$out-host-summary-$rightnow.txt

echo 'Current runlevel' >> system-summary/$out-host-summary-$rightnow.txt
echo '---------------------------------------------------------------------------------------------' >> system-summary/$out-host-summary-$rightnow.txt
runlevel >> system-summary/$out-host-summary-$rightnow.txt
echo '' >> system-summary/$out-host-summary-$rightnow.txt
echo '' >> system-summary/$out-host-summary-$rightnow.txt
echo 'System memory total' >> system-summary/$out-host-summary-$rightnow.txt
echo '---------------------------------------------------------------------------------------------' >> system-summary/$out-host-summary-$rightnow.txt
free -m | grep '^Mem:' | awk '{print $2}' >> system-summary/$out-host-summary-$rightnow.txt
echo '' >> system-summary/$out-host-summary-$rightnow.txt
echo '' >> system-summary/$out-host-summary-$rightnow.txt

echo 'Disk utilization' >> system-summary/$out-host-summary-$rightnow.txt
echo '---------------------------------------------------------------------------------------------' >> system-summary/$out-host-summary-$rightnow.txt
df >> system-summary/$out-host-summary-$rightnow.txt
echo '' >> system-summary/$out-host-summary-$rightnow.txt
echo '' >> system-summary/$out-host-summary-$rightnow.txt

echo 'CPU core count' >> system-summary/$out-host-summary-$rightnow.txt
echo '---------------------------------------------------------------------------------------------' >> system-summary/$out-host-summary-$rightnow.txt
cat /proc/cpuinfo | grep '^processor' | wc -l >> system-summary/$out-host-summary-$rightnow.txt
echo '' >> system-summary/$out-host-summary-$rightnow.txt
echo '' >> system-summary/$out-host-summary-$rightnow.txt


# Local users in /etc/passwd
cat /etc/passwd | cut -d ':' -f 1 | sort >> before/$out-local-users-$rightnow.txt

# Local users in /etc/passwd with bash access
cat /etc/passwd | grep bash$ >> before/$out-local-users-with-shell-access-$rightnow.txt

# Local groups in /etc/group
cat /etc/group | cut -d ':' -f 1 | sort >> before/$out-group-$rightnow.txt

# RPMs installed
rpm -qa | sort >> before/$out-rpm-list-$rightnow.txt

# RPMs installed count
rpm -qa | wc -l >> before/$out-rpm-count-$rightnow.txt

# System services installed
systemctl list-unit-files >> before/$out-services-$rightnow.txt

# System services enabled for to run at boot
systemctl list-unit-files | grep enabled | sort >> before/$out-services-enabled-$rightnow.txt

# SELinux enforcement policy
getenforce >> before/$out-selinux-mode-$rightnow.txt

# SELinux status output
sestatus >> before/$out-selinux-status-$rightnow.txt

# Network interface configuration
ifconfig -a | grep -E 'flags|inet' >> before/$out-ifconfig--$rightnow.txt

# TCP listening processes and ports
netstat -antp | grep LISTEN | sed s/'[0-9]\+\/'//g >> before/$out-netstat-listening-tcp-$rightnow.txt

# UDP listening processes and ports
netstat -anup | grep -E '0 0.0.0.0|0 127.0.0.1|0 ::' >> before/$out-netstat-listening-udp-$rightnow.txt

# Process list (usernames and process commands, sorted by username
ps -eo user,command --sort=user >> before/$out-processes-$rightnow.txt

# Process tree
pstree -a >> before/$out-process-tree-$rightnow.txt

# Cron jobs for root
cat /var/spool/cron/root >> before/$out-cron-root-$rightnow.txt

# DNS nameserver configuration
cat /etc/resolv.conf | grep ^nameserver >> before/$out-dns-servers-$rightnow.txt

# NTP target server configuration
cat /etc/ntp.conf | grep ^server >> before/$out-ntp-servers-$rightnow.txt

# List of directories on file system
find / -type d -print >> before/$out-directories-$rightnow.txt

# Disk utilization
df >> before/$out-disk-usage-$rightnow.txt
